### ISSUE TITLE
How to know the queue length

### ISSUE THREAD

**Issue by rogerdielrton** [SGrondin/bottleneck#10]
"Bottleneck builds a queue of requests and executes them as soon as possible."
How can I know the queue length? There is no method in "Bottleneck" class to check it.
I think that it's needed because if you issue several "limiter.submit" calls, in the corresponding callback functions is needed to test if it's the end of all requests,

**Comment by SGrondin** [comment]
Hi, you can use [nbQueued](https://github.com/SGrondin/bottleneck#nbqueued). Another way is to issue all of your `submit` calls, then `submit` another job and when that last job is called you know the queue is empty. Please let me know if you have any other questions.
