### ISSUE TITLE
Small README Fix (Gotcha)

### ISSUE THREAD

**Issue by elliot-nelson** [SGrondin/bottleneck#101]
There's a confusing section in the README, under "Gotchas":

```
// instead of this:
limiter.schedule(() => object.doSomething(arg1, arg2));
// do this:
limiter.schedule(() => object.doSomething.bind(object)(arg1, arg2));
```

I think what is intended here is that you need to do _one of the following:_

```
// either this
limiter.schedule(() => object.doSomething(arg1, arg2));
// or this
limiter.schedule(object.doSomething.bind(object, arg1, arg2));
```

(You shouldn't need to bind if it's an arrow function, only if you are passing the method directly into `schedule()`.)

**Comment by SGrondin** [comment]
Yes you are correct! Would you like to make a PR for it?

**Comment by elliot-nelson** [comment]
Sure thing!  I'll get one up tomorrow.

**Comment by SGrondin** [comment]
Merged 🎉
