### ISSUE TITLE
Group feature - improve documentation

### ISSUE THREAD

**Issue by weeco** [SGrondin/bottleneck#102]
Hey,
I believe I've got a very similiar use case as the described DNS server use case, however I am missing the documentation part which describes how you would limit requests by IP address (for example 5 requests / 10 seconds). Maybe you could explain me how I'd need to use bottleneck for the following use case:

**Use case**

I've got a REST Api which issues JSON Webtokens for authenticated users. Because I don't want to use IP addresses for rate limiting I want to rate limit on a UUID which is passed with the JWT on every request. Therefore I've got a middleware which either passes the JWT payload to the next middlewares by returning it or throwing an exception. Each UUID is allowed to send 10 requests / 5seconds, if this has been exceeded I want to throw an error (no further queueing, because it's very likely a DoS attack):

```ts
@Injectable()
export class AuthService implements OnModuleInit {
  private limiter: bottleneck.Group;

  constructor(private config: ConfigService) {}

  public async onModuleInit(): Promise<void> {
    this.limiter = new bottleneck.Group({ strategy: bottleneck.strategy.OVERFLOW, resorvoir: 10, reservoirRefreshAmount: 10, reservoirRefreshInterval: 5 * 1000 });
  }

  // This method is executed on all routes which require JWT authentication
  public async validateUser(payload: IJwtPayload): Promise<IJwtPayload> {
    // Return payload if enough tokens for that uuid are available, otherwise throw new TooManyRequestsException()
    this.limiter.key(payload.uuid).submit()
    
    return payload;
  }
```

PS: In general I am a bit confused where the queue comes in when you use "reservoirs".

**Comment by SGrondin** [comment]
Hey, you're not far off!

>In general I am a bit confused where the queue comes in when you use "reservoirs".

I think this is the source of your confusion. Any request that can't be run now due to maxConcurrent and/or reservoir will be queued.

- `maxConcurrent`/`reservoir`: make requests wait -> fills the queue
- `strategy`: how to decide which queued up requests to drop when the queue length exceeds `highWater`
- `highWater`: the maximum acceptable queue length.

With that being said, here's how I would do it:
```js
@Injectable()
export class AuthService implements OnModuleInit {
  private group: bottleneck.Group; // RENAMED. The result of group.key is a limiter.

  constructor(private config: ConfigService) {}

  public async onModuleInit(): Promise<void> {
    this.group = new bottleneck.Group({
      highWater: 0, // ADDED
      strategy: bottleneck.strategy.OVERFLOW,
      reservoir: 10, // FIXED TYPO
      reservoirRefreshAmount: 10,
      reservoirRefreshInterval: 5 * 1000
    });
  }

  // This method is executed on all routes which require JWT authentication
  public async validateUser(payload: IJwtPayload): Promise<IJwtPayload> {
    // Return payload if enough tokens for that uuid are available, otherwise throw new TooManyRequestsException()
    try {
      // The await is important here, to force exceptions to go to the catch block
      return await this.group.key(payload.uuid).schedule(() => payload);
    } catch (e: bottleneck.BottleneckError) {
      throw new TooManyRequestsException();
    }
  }
}
```
See my comments.

Important note: since you're using `reservoirRefreshInterval`, it means the user is allowed to send 10 requests in quick succession (or even in parallel) as long as they don't go over 10/5s. To slow down those requests you'd have to use `maxConcurrent` and/or `minTime`, but then they'd have to spend some time in the queue, so you'd have to set the `highWater` higher to account for that. Reminder that you can use `limiter.counts()` to inspect where your requests are in the lifecycle.

**Comment by weeco** [comment]
Thanks a ton for taking the time helping me with this one!

> Important note: since you're using reservoirRefreshInterval, it means the user is allowed to send 10 requests in quick succession (or even in parallel) as long as they don't go over 10/5s. To slow down those requests you'd have to use maxConcurrent and/or minTime

I am aware of that, however my understanding is that the job is considered as done once the callback resolves (which it immediately does because it just returns the payload). Therefore there is literally no chance that it would handle multiple requests in parallel or am I wrong here?

I could consider minTime though. Thanks for the additional note about the queue!

**Comment by weeco** [comment]
Works as intended, that was well explained. I was a bit surprised that I am supposed to use the `schedule()` method instead of the `submit()` method as shown in the readme example for the DNS server.

**Comment by SGrondin** [comment]
`schedule()` is for Promises, `submit()` is for old school async functions that take a callback `cb` as their last argument and then resolve by calling `cb(error, result)`.

I've updated the README example since in 2019 99% of people will need to use `schedule()`.
