### ISSUE TITLE
Upgrade deps and run tests on travis

### ISSUE THREAD

**Issue by maikelmclauflin** [SGrondin/bottleneck#104]
have not investigated too much, but it seems that i am unable to use the wrap method on travis cli. i noted that travis is not utilized for testing so i set it up.

**Comment by SGrondin** [comment]
Could you show me a reproducible example of how you're using wrap?

Thanks

**Comment by maikelmclauflin** [comment]
Hey sorry didn't close, finally found the issue before i went to sleep yesterday. Issue was on my end. didn't have the correct redis url going into docker container.

As far as the minimatch, it seems to be an ejs-cli dep. yeah, i agree, no need to add deps. was just running `npm audit` and found that a few had vulnerabilities. hence, upgrade / reinstall latest. can modify after finished working today to make sure redis is setup on travis.

**Comment by SGrondin** [comment]
That would be awesome 😄 I'll merge it once the issues I mentioned in the PR are resolved. Hopefully you'll have the time to get it all done, but if you don't then I'll do it this weekend.

**Comment by maikelmclauflin** [comment]
Fair enough
