### ISSUE TITLE
Cannot read property 'priority' of undefined

### ISSUE THREAD

**Issue by 50l3r** [SGrondin/bottleneck#109]
Hi all,

I have a problem with priority with nested schedules. I write a code that get keywords and process ajax calls for each keyword:

Each keyword have multiple pages. 2 pages each second and 1 keyword each second. Only 1 concurrent job.

    const limiterPages = new Bottleneck({
        maxConcurrent: 1,
        minTime: 1000,
    });

    this.keywords.forEach((keyword) => {
        limiterPages.submit(this.pages, this.aws, keyword.keyword, (response) => {
            if (response.response) {
                const Pages = response.pages;
                let CurrentPage = 1;
                let Products = [];

                const limiterProducts = new Bottleneck({
                    maxConcurrent: 1,
                    minTime: 500,
                });

                limiterProducts.schedule(() => this.process(keyword.keyword, CurrentPage)).then(async (items) => {
                    items.forEach((item) => {
                        Products.push({
                            sku: item.sku,
                            name: item.name,
                            price: item.price,
                            image: item.image,
                        });
                    });

                    const PagesRemain = Pages - CurrentPage;

                    if (Products.length === 100 || (Products.length < 100 && PagesRemain <= 10)) {
                        const sync = await this.sdk.products().sync(Products);

                        Products = [];
                    }

                    CurrentPage++;
                }).catch((awserr) => {
                    
                });
            }
        });
    });

I recieve this error:

`    (node:17896) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'priority' of undefined
    at Object.exports.load (D:\Git\michollo\bots\amazon\node_modules\bottleneck\lib\parser.js:8:30)
    at Bottleneck.submit (D:\Git\michollo\bots\amazon\node_modules\bottleneck\lib\Bottleneck.js:446:26)
    at keywords.forEach (D:\Git\michollo\bots\amazon\index.js:40:34)
    at Array.forEach (<anonymous>)
    at AmazonBOT.init (D:\Git\michollo\bots\amazon\index.js:39:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by SGrondin** [comment]
This is happening because the first argument to `.submit()` must be a function or an options object. `this.pages` is `undefined`.

`.submit()` exists for old school Node functions in the continuation passing style, with a callback function that your request **must call**. For your use case you need to use `.schedule()`.

Make sure you use `.schedule()` and that the first argument to your new `.schedule()` is also a function. Finally, you'll need to `return` the value returned by `limiterProducts.schedule` or your new outer `.schedule()` will never know that your job is still processing!

Feel free to paste your fixed code and I'll validate/edit it. There's too many things slightly wrong here and I can't fix them without knowledge of your code, but hopefully this will help!

**Comment by 50l3r** [comment]
> This is happening because the first argument to `.submit()` must be a function or an options object. `this.pages` is `undefined`.
> 
> `.submit()` exists for old school Node functions in the continuation passing style, with a callback function that your request **must call**. For your use case you need to use `.schedule()`.
> 
> Make sure you call `limiterPages.schedule` instead and that its first argument is also a function! You'll also need to `return` the value returned by `limiterProducts.schedule` or your new `limiterPages.schedule` will never know that its job is still processing!
> 
> Feel free to paste your fixed code and I'll validate/edit it. There's too many things slightly wrong here and I can't fix them without knowledge of your code, but hopefully this will help!

I solved it passing this.pages callback function to Promise :)
