### ISSUE TITLE
Remove all jobs in flight before adding more

### ISSUE THREAD

**Issue by paolotremadio** [SGrondin/bottleneck#117]
Hi,

Is there a way to cancel all jobs that are currently running and queued before adding some more to the queue? 

I use bottleneck for this project: https://github.com/paolotremadio/homebridge-hue-scenes

I send commands to a phisical hub (Philips Hue) which has unpredictable loads. I’d like to cancel all jobs in queue before setting a new scene, in order to avoid unexpected results. 

Thanks!

**Comment by SGrondin** [comment]
Hey, I'm a big Hue fan, almost all of my lights are connected to my Hue hub. I'm glad to see Bottleneck being used in this area.

> Is there a way to cancel all jobs that are currently running and queued before adding some more to the queue?

There's no way in JavaScript to cancel execution of something that's already running, **but** I think `limiter.stop({ dropWaitingJobs: true });` will work for your needs. [Here](https://github.com/SGrondin/bottleneck#stop) are the docs for it.

Once you've called `.stop()` on a limiter, that limiter is forever destroyed, it won't accept new jobs, so here's how I would solve your problem:

This is example code, I haven't run it
```js
const settings = {
  maxConcurrent: 1,
  minTime: 1000
  // other settings...
}

let limiter = new Bottleneck(settings)

const removeAllJobs = async function (limiter, settings) {
  await limiter.stop({ dropWaitingJobs: true })
  const newLimiter = new Bottleneck(settings)
  return newLimiter
}

// ... use the limiter ...

// When ready to remove all jobs and add more:
limiter = await removeAllJobs(limiter, settings)

// ... use this new limiter ...
```

Does that make sense? I hope it answers your question.

**Comment by SGrondin** [comment]
Please reopen the issue if you have additional questions.

**Comment by paolotremadio** [comment]
Thanks. That did work indeed. I've just released a new version of my plugin :)
