### ISSUE TITLE
reservoirIncreaseAmount

### ISSUE THREAD

**Issue by tomblanchard** [SGrondin/bottleneck#119]
First of all, this package is great - it's been difficult to find a simple job queue which already comes with a rate limiter built in so thank you so much for this.

Can we throttle using a leaky bucket algorithm? I'm attempting to use Bottleneck to throttle my requests to the Shopify API to avoid hitting their 2 calls per second limit.

https://help.shopify.com/en/api/getting-started/api-call-limit

My current config is:

```
{
  minTime: 500,
  maxConcurrent: 1
}
```

This works and never goes over the Shopify API limit but it can be pretty slow and I'd like to take advantage of the Shopify API's burst behavior. I should initially be able to make a burst of 40 concurrent requests, then after that, requests should conform to 2 calls per second.

I tried experimenting with the `reservoir` settings:

```
{ 
  reservoir: 40,
  reservoirRefreshAmount: 40,
  reservoirRefreshInterval: 60 * 1000
```

This is _almost_ correct but it makes 40 calls, waits 60 seconds, then makes another 40 calls and so on. I need it to reset to 2 calls per second after the first burst of 40.

Is this possible?

**Comment by TheGame2500** [comment]
@tomblanchard did you try

```javascript
{ 
  reservoir: 40,
  reservoirRefreshAmount: 2,
  reservoirRefreshInterval: 1000
}
```

or if using clustering

```javascript
{ 
  reservoir: 40,
  reservoirRefreshAmount: 10,
  reservoirRefreshInterval: 5000
}
```
?

**Comment by tomblanchard** [comment]
Hey @TheGame2500 - thanks a lot for that, I tried your solution and it works, but only for the first burst of requests, e.g.

- Open browser window (I'm using Bottleneck in the context of an Express app)
- A burst of 40 concurrent requests fire and all subsequent requests get fired at 2 calls per second
- Wait a minute or so (at this point, the Shopify API bucket will be fully refilled to 40)
- Refresh the page and all requests get fired at 2 calls per second

Is there anything we can do here to persist the burst behaviour after the first burst?

**Comment by SGrondin** [comment]
Hey @tomblanchard I apologize for not being able to respond yet. Tomorrow I should have the time to properly read and dissect your code example.

Thank you @TheGame2500 for making the suggestion.

**Comment by SGrondin** [comment]
If I understand correctly, if you were to fire 40 requests, then not fire any for 10 seconds, you would then expect to be able to fire 20 requests immediately? In other words, every second grants 2 more requests up to a maximum of 40?

If so, you could achieve this behavior by using something similar to this:
```js
var Bottleneck = require("bottleneck/es5");

var limiter = new Bottleneck({
  reservoir: 40 // initial amount
});

var interval = setInterval(() => {
  // Every second, increment the reservoir by 2, up to a maximum of 40
  limiter.currentReservoir()
  .then((reservoir) => {
    var incrBy = Math.min(2, 40 - reservoir)
    if (incrBy > 0) {
      return limiter.incrementReservoir(incrBy)
    }
  })
}, 1000)
```
Please let me know if that works for you,

Thanks!

**Comment by TheGame2500** [comment]
@SGrondin can you perhaps add a reservoirIncreaseAmount property? Or at least add a warning sign in the docs near the reservoirRefreshAmount property because that's how I expected to work

**Comment by SGrondin** [comment]
Oh I like the idea of `reservoirIncreaseAmount`! That way it would be clear how it differs from `reservoirRefreshAmount`.

**Comment by tomblanchard** [comment]
@SGrondin Thanks so much for getting back to me.

I just tested your solution out and it works great for my reduced test case but I'm struggling to figure out how I'd implement it in the app I'm building.

It's an Express app with a simple authentication middleware, like this:

```
var express = require("express");
var session = require("express-session");
var Shopify = require("shopify-api-node");
var Bottleneck = require("bottleneck/es5");

var app = express();
var port = 3000;

var group = new Bottleneck.Group({
  reservoir: 35
});

app.use(session({
  secret: "secret",
  resave: false,
  saveUninitialized: true
}));

function authMiddleware(req, res, next) {
  req.session.shopName = req.session.shopName || req.query.shopName;
  req.session.apiKey = req.session.apiKey || req.query.apiKey;
  req.session.password = req.session.password || req.query.password;

  if (!req.session.shopName || !req.session.apiKey || !req.session.password) {
    return res.redirect("/install");
  }

  return next();
};

app.get("/", authMiddleware, (req, res) => {
  var shopName = req.session.shopName;
  var apiKey = req.session.apiKey;
  var password = req.session.password;

  var shopify = new Shopify({ shopName, apiKey, password });

  shopify.on("callLimits", (limits) => console.log(limits));

  function requests() {
    return Array.from({ length: 100 }, () => {
      return group.key(shopName).schedule(() => shopify.shop.get());
    });
  };

  Promise.all(requests())
    .then((resShop) => {
      return res.json(resShop);
    });
});

app.listen(port, () => {
  console.log(`App listening on port ${port}!`)
});
```

I'm just struggling to figure out where I'd drop that `setInterval` block, my gut tells me to put it in `authMiddleware` before `return next();`, but that'd great a new interval on every page load.

Thanks again for working through this with me, it's much appreciated.

**Comment by SGrondin** [comment]
Ah, you're using a group. You'll need to do it at the top level, outside of the request lifecycle. In your example, paste this snippet immediately after creating the group:
```js
group.on("created", function (limiter, key) {
  var interval = setInterval(() => {
    // Clear interval if the limiter has been GC'd
    if (group.instances[key] == null) {
      clearInterval(interval);
      return;
    }

    // Every second, increment the reservoir by 2, up to a maximum of 40
    limiter.currentReservoir()
    .then((reservoir) => {
      var incrBy = Math.min(2, 40 - reservoir);
      if (incrBy > 0) {
        return limiter.incrementReservoir(incrBy);
      }
    });
  }, 1000);
});
```
Here we're using the group's `"created"` event to run some code every time a new limiter is created inside the group. That's where we create the interval. Unfortunately we also have the handle the case where the limiter is removed.

I think I'll have the time to implement and release `reservoirIncreaseAmount` within a week or two, and that will make all of this code unnecessary, Bottleneck will handle it all automatically.

**Comment by tomblanchard** [comment]
@SGrondin Awesome, that worked perfectly - thank you SO much.

Looking forward to seeing the release of `reservoirIncreaseAmount` :)

Thanks again Simon.

**Comment by SGrondin** [comment]
You're welcome 😄

**Comment by SGrondin** [comment]
🎉 I've released v2.18.0, it adds the concept of [Increase Intervals](https://github.com/SGrondin/bottleneck#increase-interval). There are 3 new settings for this feature: `reservoirIncreaseInterval`, `reservoirIncreaseAmount` and `reservoirIncreaseMaximum`.

Please give it a try and let me know if it works as expected for you! 😄

**Comment by tomblanchard** [comment]
@SGrondin This works perfectly! You are awesome, thanks so much. <3

**Comment by SGrondin** [comment]
You're welcome! 😊  Your question lead to a really neat feature. It makes so much sense, I don't understand why it took so long to add it in.
