### ISSUE TITLE
Cannot specify custom Promise Library

### ISSUE THREAD

**Issue by codechaotic** [SGrondin/bottleneck#12]
I'm running into an error trying to substitute Q as my promise library.

In the README it states that 

> It's also possible to replace the Promise library used:
> ```
> var Bottleneck = require("bottleneck");
> Bottleneck.Promise = myPromiseLibrary;
>
> var limiter = new Bottleneck(maxConcurrent, minTime, highWater, strategy);
> ```

However the following code does not create a Q Promise

```js
var Bottleneck = require('bottleneck');
var Q = require('q');
Bottleneck.Promise = Q.Promise;

var limiter = new Bottleneck(1, 1000);

var p = limiter.schedule(function() {
  return Q.resolve(true);
});

console.log(Q.isPromise(p))  // false
```

Either this is a bug or I'm not setting this up correctly. Please help?

**Comment by SGrondin** [comment]
Hi @codechaotic it's an issue in the docs... really sorry for this.

Instead of
```js
Bottleneck.Promise = Q.Promise;
```
do
```js
Bottleneck.prototype.Promise = Q.Promise;
```

I'm releasing `1.10.1` right now to make it update on [npm](js.com/package/bottleneck) as well.

**Comment by codechaotic** [comment]
Thank you so much for your prompt response. Your suggestion worked! You're awesome.

**Comment by SGrondin** [comment]
Thanks! :)
