### ISSUE TITLE
Limit 10 request per second

### ISSUE THREAD

**Issue by Murshidv4** [SGrondin/bottleneck#120]
My requirement is to limit 10 requests per second. Can you please confirm that this code is enough.?

```
const limiter = new Bottleneck({
			maxConcurrent: 1,
			minTime: 101010
});
```

**Comment by SGrondin** [comment]
Sorry for the slow response 😅 

To limit it to 10 requests per second, use this:
```js
const limiter = new Bottleneck({
  maxConcurrent: 1,
  minTime: 100
});
```
*Important*: if your requests can sometimes take longer than 100ms to complete it will be running less than 10 requests per second (basic math). If you want to keep starting new jobs at a rate of 10/s **even if the one already running has not completed yet** then increase `maxConcurrent`.

**Comment by SGrondin** [comment]
Please let me know if you run into any issues! :)
