### ISSUE TITLE
"Job received" Event

### ISSUE THREAD

**Issue by lp-wodell** [SGrondin/bottleneck#124]
Would be great to have an event that fired when a job is received by the bottleneck. Our code is sending to a single instance of a bottleneck from a large variety of places and modules which makes this hard to track.

If there is an existing way to do this then please let me know!

**Comment by SGrondin** [comment]
That's a great idea and it's easy to implement. I'll do it this weekend!

**Comment by lp-wodell** [comment]
Now **that** is service! Thank you so much.

**Comment by SGrondin** [comment]
Sorry for the delay! It took me some time last weekend to realize that it was better to make this feature local to a limiter inside a Cluster. Once I realized that, it didn't take much time to implement.

Bottleneck 2.19.0 adds the following events: `received`, `queued`, `scheduled`, `executing` and `done`. They map to [Jobs Lifecycle transitions](https://github.com/SGrondin/bottleneck/blob/master/README.md#jobs-lifecycle). 🎉 

For your use case, you would use either `received` or `queued`, depending on your needs.

`received` is triggered immediately and for every `schedule()`/`submit()`/`wrapped()` call.

`queued` is triggered after the limiter has validated the current queue size against the `highWaterMark` option. This event happens almost immediately after `received`, but it will not be triggered if the job is not accepted into the queue.

**Comment by lp-wodell** [comment]
Thank you Simon! I think others will find this very useful too where a bottleneck instance can be accessed from lots of different points in the code.

**Comment by SGrondin** [comment]
I agree, it's such an obvious feature in retrospect that I'm surprised I didn't think about it and no one suggested it earlier.
