### ISSUE TITLE
Callback when queue is empty?

### ISSUE THREAD

**Issue by olalonde** [SGrondin/bottleneck#13]
Would be nice for limiter objects to call a callback every time their queue is drained.

**Comment by SGrondin** [comment]
Hi,

This is definitely on the roadmap, along with a callback when a request was dropped.

**Comment by SGrondin** [comment]
This was implemented in [v1.11.0](https://github.com/SGrondin/bottleneck#events). Feedback appreciated!

**Comment by olalonde** [comment]
Thanks! I absolutely needed that feature so ended up writing my custom function but I will know for the future. :+1:

**Comment by SGrondin** [comment]
Cool! If it's public code I'd be curious to see what your implementation looks like. Do you have a link?
