### ISSUE TITLE
BottleneckError: Invalid job status RUNNING, expected EXECUTING

### ISSUE THREAD

**Issue by gr2m** [SGrondin/bottleneck#132]
I got this error in production from the WIP GitHub app

Asked me to create an issue so here you go. Is there anything I can help with to debug it?

I use a cluster setup with Redis

![image](https://user-images.githubusercontent.com/39992/62184516-526aeb00-b313-11e9-8724-8c3caf5eb14c.png)

**Comment by SGrondin** [comment]
Thanks for reporting this. Has it happened before or since? I'll look into it as soon as possible

**Comment by gr2m** [comment]
It's the first time I saw it. Sentry has a single occurrence of it. Thanks Simon!

**Comment by SGrondin** [comment]
This is fixed in [v2.19.5](https://github.com/SGrondin/bottleneck/releases/tag/v2.19.5) 🎉
