### ISSUE TITLE
I get lots of tasks "stuck" in "running" state without providing the minTime

### ISSUE THREAD

**Issue by GuyEphraim** [SGrondin/bottleneck#134]
My code is highly async and I schedule from many places to a single limiter.
some of the jobs I schedule get "stuck" with "running" status and never get executed.
the bottleneck configuration is empty and docs say only something about the minTime that can get to the running state.

**Comment by SGrondin** [comment]
Hi, thanks for opening this issue. Can you please show how your limiter is created? And please show an example of how you schedule a job.

Thank you!

**Comment by GuyEphraim** [comment]
`   this.limiter = new BottleNeck({});
`

On another class with a reference to the limiter I do:
```
        return this.limiter.schedule(async () => {
            console.log(1);
          });
```

the console log is never reached
if I print the counts I see something like:
limiter: {"RECEIVED":0,"QUEUED":0,"RUNNING":0,"EXECUTING":0}
limiter: {"RECEIVED":0,"QUEUED":0,"RUNNING":1,"EXECUTING":0}
limiter: {"RECEIVED":0,"QUEUED":0,"RUNNING":2,"EXECUTING":0}
limiter: {"RECEIVED":0,"QUEUED":0,"RUNNING":3,"EXECUTING":0}
limiter: {"RECEIVED":0,"QUEUED":0,"RUNNING":4,"EXECUTING":0}
limiter: {"RECEIVED":0,"QUEUED":0,"RUNNING":5,"EXECUTING":0}
limiter: {"RECEIVED":0,"QUEUED":0,"RUNNING":6,"EXECUTING":0}
limiter: {"RECEIVED":0,"QUEUED":0,"RUNNING":7,"EXECUTING":0}

**Comment by SGrondin** [comment]
Hmm interesting... the default behavior should be to essentially be a passthrough. I'll take a closer look as soon as possible.

**Comment by GuyEphraim** [comment]
essentially I'd like to know what are the cases my job goes into "running" state given my configuration

**Comment by SGrondin** [comment]
I finally had time to look into this. I can't seem to reproduce your issue. Here's what I'm doing:
```js
const Bottleneck = require('bottleneck')
const limiter = new Bottleneck({})

const wait = (ms) => new Promise((resolve, reject) => setTimeout(resolve, ms))

async function main() {
  limiter.schedule(async () => console.log(1))
  limiter.schedule(async () => console.log(2))
  limiter.schedule(async () => console.log(3))
  limiter.schedule(async () => console.log(4))
  limiter.schedule(async () => console.log(5))

  console.log(limiter.counts())
  await wait(100)
  console.log(limiter.counts())
}


main()
.catch(e => {
  console.log('UNCAUGHT EXCEPTION', e)
  process.exit(1)
})
```
And it prints the correct result:
```js
{ RECEIVED: 5, QUEUED: 0, RUNNING: 0, EXECUTING: 0 }
1
2
3
4
5
{ RECEIVED: 0, QUEUED: 0, RUNNING: 0, EXECUTING: 0 }
```
If I set the limiter options to `{ trackDoneStatus: true }` then I see:
```js
{ RECEIVED: 5, QUEUED: 0, RUNNING: 0, EXECUTING: 0, DONE: 0 }
1
2
3
4
5
{ RECEIVED: 0, QUEUED: 0, RUNNING: 0, EXECUTING: 0, DONE: 5 }
```
Is it possible you're using `submit()` and not calling the callback?

The only way you can have multiple jobs in the `RUNNING` state for a long period of time is if you set a very high `minTime` without setting a `maxConcurrent` value. The docs actively recommend against skipping `maxConcurrent`, but even with just `minTime` your jobs will eventually reach `EXECUTING`.

Are you certain your limiter is instantiated with `{}`?

Is it possible that you're using `updateSettings()`?

**Comment by GuyEphraim** [comment]
I also couldn't reproduce it on a small scale project.
about your questions, I use only schedule
however I'm having many instances of the module around 20, all with the
same configuration, without the minTime. also I've never called
updateSettings

**Comment by GuyEphraim** [comment]
also replacing the new Bottleneck({}) with { schedule: fn => fn() } made it
work. meaning nothing else is being called

**Comment by SGrondin** [comment]
Thanks, this helps. I have a few more questions to understand what's happening:

- How many jobs are you adding to the limiter shortly after it starts?
- How high did you see the `RUNNING` number go?
- Could you try adding a `maxConcurrent` and see if that works?
- What is your use case for using a limiter without any settings?

**Comment by SGrondin** [comment]
I've been trying a lot of different cases to try to reproduce this issue for the last hour, without luck. When I make 10,000 pile up in `RECEIVED`, then let them go, I never see more than 1 in `RUNNING`. Same when I make them all pile up in `QUEUED` before allowing them through.

Are you running this on the browser or in Node? Are you using Clustering?

**Comment by SGrondin** [comment]
I would normally edit my comment to add something, but you're using email. I forgot to ask: Can you try adding a listener for the `'error'` event?

Thanks!

**Comment by GuyEphraim** [comment]
I've been working on reducing the scenario to the smallest I could, which
still reproduce the issue.
so, I managed to reproduce it using only one bottleneck, so it is probably
not related to load.
now for your questions,
* the issue starts on the first job I add to the limiter - none of them are
executing, all are stuck in "running" state
* My test went up to 58 jobs, so the the number was 58
* my first test was with maxConcurrent, it didn't work so I've removed it,
if I re-add it it has no effect
* I'm running inside with node 10.15 and no clustering
* I did add a listener on both failed and error but nothing called there

I really appreciate your help here.

Thanks.

**Comment by SGrondin** [comment]
Woah I'm totally stumped!! 😵

I'll try again to reproduce it but I'm totally at a loss. This is crazy. Any scenario I can run would be amazing, even if it's not trivial.

Could you try adding an event listener for the `'debug'`, give an ID to *one* job and see what debug messages you get for that job ID?

**Comment by GuyEphraim** [comment]
before each schedule I've added a print of counts() and made the id of the
jobs running number. here is a snippet of the logs

bottleNeck.counts() : {"RECEIVED":0,"QUEUED":0,"RUNNING":4,"EXECUTING":0}
bottleneck Event triggered: received
bottleneck Event triggered: queued
bottleneck Draining 5
bottleneck Drained 5
bottleneck Event triggered: empty
bottleneck Event triggered: scheduled
bottleNeck.counts() : {"RECEIVED":0,"QUEUED":0,"RUNNING":5,"EXECUTING":0}
bottleneck Event triggered: received
bottleneck Event triggered: queued
bottleneck Draining 6
bottleneck Drained 6
bottleneck Event triggered: empty
bottleneck Event triggered: scheduled
bottleNeck.counts() : {"RECEIVED":0,"QUEUED":0,"RUNNING":6,"EXECUTING":0}
bottleneck Event triggered: received
bottleneck Event triggered: queued
bottleneck Draining 7
bottleneck Drained 7
bottleneck Event triggered: empty
bottleneck Event triggered: scheduled
bottleNeck.counts() : {"RECEIVED":0,"QUEUED":0,"RUNNING":7,"EXECUTING":0}
bottleneck Event triggered: received
bottleneck Event triggered: queued
bottleneck Draining 8
bottleneck Drained 8
bottleneck Event triggered: empty
bottleneck Event triggered: scheduled
bottleNeck.counts() : {"RECEIVED":0,"QUEUED":0,"RUNNING":8,"EXECUTING":0}
bottleneck Event triggered: received
bottleneck Event triggered: queued
bottleneck Draining 9
bottleneck Drained 9
bottleneck Event triggered: empty
bottleneck Event triggered: scheduled
bottleNeck.counts() : {"RECEIVED":0,"QUEUED":0,"RUNNING":9,"EXECUTING":0}
bottleneck Event triggered: received
bottleneck Event triggered: queued
bottleneck Draining 10
bottleneck Drained 10
bottleneck Event triggered: empty
bottleneck Event triggered: scheduled

**Comment by GuyEphraim** [comment]
added a print for all params:
§bottleNeck.counts() : {"RECEIVED":1,"QUEUED":0,"RUNNING":3,"EXECUTING":0}
bottleneck 0=Event triggered: received, 1=[args=[], priority=5, weight=1,
expiration=null, id=5]
bottleneck 0=Event triggered: queued, 1=[args=[], priority=5, weight=1,
expiration=null, id=4, reachedHWM=false, blocked=false]
bottleneck 0=Draining 4, args=[], priority=5, weight=1, expiration=null,
id=4
bottleneck 0=Drained 4, success=true, args=[], priority=5, weight=1,
expiration=null, id=4
bottleneck 0=Event triggered: scheduled, 1=[args=[], priority=5, weight=1,
expiration=null, id=4]
bottleneck 0=Event triggered: queued, 1=[args=[], priority=5, weight=1,
expiration=null, id=5, reachedHWM=false, blocked=false]
bottleneck 0=Draining 5, args=[], priority=5, weight=1, expiration=null,
id=5
bottleneck 0=Drained 5, success=true, args=[], priority=5, weight=1,
expiration=null, id=5
bottleneck 0=Event triggered: empty, 1=[]
bottleneck 0=Event triggered: scheduled, 1=[args=[], priority=5, weight=1,
expiration=null, id=5]
bottleNeck.counts() : {"RECEIVED":0,"QUEUED":0,"RUNNING":5,"EXECUTING":0}
bottleneck 0=Event triggered: received, 1=[args=[], priority=5, weight=1,
expiration=null, id=6]
bottleneck 0=Event triggered: queued, 1=[args=[], priority=5, weight=1,
expiration=null, id=6, reachedHWM=false, blocked=false]
bottleneck 0=Draining 6, args=[], priority=5, weight=1, expiration=null,
id=6
bottleneck 0=Drained 6, success=true, args=[], priority=5, weight=1,
expiration=null, id=6
bottleneck 0=Event triggered: empty, 1=[]
bottleneck 0=Event triggered: scheduled, 1=[args=[], priority=5, weight=1,
expiration=null, id=6]
bottleNeck.counts() : {"RECEIVED":0,"QUEUED":0,"RUNNING":6,"EXECUTING":0}
bottleneck 0=Event triggered: received, 1=[args=[], priority=5, weight=1,
expiration=null, id=7]
bottleneck 0=Event triggered: queued, 1=[args=[], priority=5, weight=1,
expiration=null, id=7, reachedHWM=false, blocked=false]
bottleneck 0=Draining 7, args=[], priority=5, weight=1, expiration=null,
id=7
bottleneck 0=Drained 7, success=true, args=[], priority=5, weight=1,
expiration=null, id=7
bottleneck 0=Event triggered: empty, 1=[]
bottleneck 0=Event triggered: scheduled, 1=[args=[], priority=5, weight=1,
expiration=null, id=7]
bottleNeck.counts() : {"RECEIVED":0,"QUEUED":0,"RUNNING":7,"EXECUTING":0}
bottleneck 0=Event triggered: received, 1=[args=[], priority=5, weight=1,
expiration=null, id=8]
bottleneck 0=Event triggered: queued, 1=[args=[], priority=5, weight=1,
expiration=null, id=8, reachedHWM=false, blocked=false]
bottleneck 0=Draining 8, args=[], priority=5, weight=1, expiration=null,
id=8
bottleneck 0=Drained 8, success=true, args=[], priority=5, weight=1,
expiration=null, id=8
bottleneck 0=Event triggered: empty, 1=[]
bottleneck 0=Event triggered: scheduled, 1=[args=[], priority=5, weight=1,
expiration=null, id=8]

**Comment by GuyEphraim** [comment]
any news on the issue?

**Comment by SGrondin** [comment]
I just came back from vacation and I still cannot reproduce it. Did you try adding a listener for the 'error' event?

**Comment by GuyEphraim** [comment]
yes, nothing there

**Comment by GuyEphraim** [comment]
any news?

**Comment by SGrondin** [comment]
Sorry, I haven't had time/energy to work on this 😞 
If you could post an example I can run I'm sure I'll be able to fix it in no time. I'm just not able to reproduce it and nothing in the code should even make it possible at all.

**Comment by GuyEphraim** [comment]
I found the issue!!!

 I'm using a module called 'mockdate'. I use this module in my tests to test how data is effected over time. this module breaks the functionality of bottleneck

bottleneck is very sensitive to date changes


here is a test example:


```
const mockdate = require('mockdate');
const Bottleneck = require('bottleneck');
test('test bottleneck without mock date', (done)=>{
  const limiter  = new Bottleneck();

  limiter.schedule(async ()=>{ done(); })

});

test('test bottleneck with mock date', (done)=>{
  const limiter  = new Bottleneck();

  const yesterday = new Date();
  yesterday.setDate(yesterday.getDate()-1);
  yesterday.setHours(0,0,0,0);
  mockdate.set(yesterday);

  limiter.schedule(async ()=>{ done(); })
});
```

**Comment by SGrondin** [comment]
WOOHOO! I'm relieved you found out what it was.

>bottleneck is very sensitive to date changes

Oh yeah, it relies on time only moving forward. In your tests I suggest you do the time changes before creating a limiter.

**Comment by SGrondin** [comment]
I added a note to the docs about using tools that change time. I don't see a way and I don't think Bottleneck should be able to deal with these time jump events.

**Comment by GuyEphraim** [comment]
thanks
