### ISSUE TITLE
question: undocumented rate limits

### ISSUE THREAD

**Issue by endquote** [SGrondin/bottleneck#149]
I'm consuming an API that has an unspecified rate limit. When the rate limit is hit, it will respond with a 403 and a header indicating how long to wait before attempting again. Can I catch that 403 within bottleneck, read that header, and adjust the queue dynamically?

I'm sure that I could use bottleneck to slow down my requests to a rate that works through trial and error, but if the limit changes, I'd just have to figure it out again.

**Comment by xcao65** [comment]
You can.
```
const response = await limiter.schedule(postCallback, header, body);

limiter.on(‘failed’, async (error) => {
  if (error.code == 403) {
    return error.timeToWait;
  }
});

const postCallback = (header, body) => {
  const response = fetch(‘POST’, {header, body,});
  if (!response.ok) {
// define a custom HTTP error type
    customHTTPError = new CustomHttpError(‘response.error.message’);
    customHTTPError.code = response.error.code;
    custom
    throw customHTTPError;
  }
}
```

**Comment by endquote** [comment]
Ah I see, thanks.

Since I wasn't able to figure it out at the time, I ended up combining [p-retry](https://github.com/sindresorhus/p-retry) and [p-queue](https://github.com/sindresorhus/p-queue).
