### ISSUE TITLE
Failed job retries immediately despite returning 60000 from the failed event

### ISSUE THREAD

**Issue by sclynes** [SGrondin/bottleneck#178]
Here is the code I am running

	constructor(proxy, rate, concurrency) {
		this.proxy = got.extend({ agent: {https: proxy} });
		this.limiter = new Bottleneck({minTime: rate, maxConcurrent: concurrency});	//rate limiting per proxy
		this.limiter.on("failed", async (error, jobInfo) => {
			const id = jobInfo.options.id;
			console.warn(`Job ${id} failed: ${error}`);
			console.log(`Retrying job ${id} in 60 Seconds!`);
			return 60000;
		});

		this.limiter.on("retry", (error, jobInfo) => console.log(`Now retrying ${jobInfo.options.id}`));	
	}

**Comment by jcristovao** [comment]
I'm facing this exact same problem - did you find a solution?

**Comment by sclynes** [comment]
I don’t have access to the code any more but I think I remember it being a non issue. The on retry event is always fired off immediately but the job itself doesn’t start until the specified time. 

you can try limiting the number of jobs to just 1 or 2 and have it fail intentionally to confirm this.
