### ISSUE TITLE
How to know when the last operation is finished?

### ISSUE THREAD

**Issue by hanouard** [SGrondin/bottleneck#24]
The empty event is called when the nbQueued() drops to 0. Is there another event that will be emitted when the last scheduled Promise is done?

**Comment by SGrondin** [comment]
No, you could wrap your last promise in a function that calls a handler to tell you when it's done, but an `empty` event could be added to Bottleneck fairly easily. Thanks for the suggestion, I'll look into it and get back to you.

**Comment by SGrondin** [comment]
@hanouard Version `1.14.0` adds the `idle` event and a few other goodies. Check it out [here](https://github.com/SGrondin/bottleneck/releases/tag/v1.14.0).

Thank you for your suggestion and for using this library.

**Comment by mikila85** [comment]
idle doesnt want to fire :(

**Comment by mikila85** [comment]
if anyone ever encounters this, idle works... the timeout doesnt so if one of the workers is stuck it keeps living, just implement your own timeout and everything works fine :)
