### ISSUE TITLE
.stopAll() throws an error

### ISSUE THREAD

**Issue by DomVinyard** [SGrondin/bottleneck#25]
Does stopAll work with .schedule()?

I have a bunch of promises lined up and calling stopAll() throws an uncaught exception

**Comment by SGrondin** [comment]
It should definitely not throw. I'll try to reproduce it. If you can post a stacktrace of that exception it would be helpful. Thank you.

**Comment by DomVinyard** [comment]
Heya, thank you, really appreciate your help. This is the line that threw:

TypeError: Cannot read property 'timeout' of undefined                                                      
    at Bottleneck.stopAll (/Users/dvinyard/Dev/Project/node_modules/bottleneck/lib/Bottleneck.js:311
:23) 

The _running array appears to be undefined. If I can do anything to help debug please let me know :)

**Comment by DomVinyard** [comment]
This is what console.log(limiter) looks like just before it throws:

<img width="486" alt="screen shot 2016-10-28 at 09 42 49" src="https://cloud.githubusercontent.com/assets/1271197/19800287/05fe5614-9cf3-11e6-96d5-2b89ce365c36.png">
<img width="502" alt="screen shot 2016-10-28 at 09 42 34" src="https://cloud.githubusercontent.com/assets/1271197/19800288/061a0a94-9cf3-11e6-858c-d6cbb66b63b6.png">

**Comment by SGrondin** [comment]
It doesn't happen in every case, but I was able to reproduce it. Fix coming soon.

**Comment by SGrondin** [comment]
Fixed in [v1.15.0](https://github.com/SGrondin/bottleneck/releases/tag/v1.15.0). Thank you for reporting this issue.

**Comment by DomVinyard** [comment]
brilliant, thank you
