### ISSUE TITLE
Cluster documentation incorrect

### ISSUE THREAD

**Issue by ChadMC** [SGrondin/bottleneck#3]
The code example for creating a cluster is incorrect. It is missing the "new" keyword on this line:

var cluster = Bottleneck.Cluster(maxConcurrent, minTime, highWater, strategy);

**Comment by SGrondin** [comment]
Thank you!

**Comment by erichedstrom** [comment]
Thanks, @ChadMC ! @SGrondin , looks like the npmjs.com page won't pick up this change until you push a new release.

**Comment by SGrondin** [comment]
I just published v1.7.2 to solve this once and for all!
