### ISSUE TITLE
How to pause the queue?

### ISSUE THREAD

**Issue by rlayne** [SGrondin/bottleneck#32]
I note that there is a documented function to stop (and remove all entries in) the queue, but is there a way of temporarily pausing (and unpausing) _execution_ of a currently executing queue _without_ destroying the remaining items in the queue?  To be clear, say I populate a queue with tasks that are presently executing. I would like to temporarily suspend execution of the tasks. Perhaps I'll add new tasks whilst the execution of the queue is suspended.  Then I would like to be able to have the queue begin executing tasks again, with respect to any changes to the queue during it's suspended phase.

I imagine it's possible to clone the queue prior to calling the function to stop the queue, then repopulating it, but there's probably a less destructive way that I'm missing :) If not - then some tips on how to accomplish this would be wonderfully helpful.  Thanks in advance.

**Comment by rlayne** [comment]
I'm sorry, it occured to me that changing the reservoir to 0 accomplishes this. You can then change the reservoir back to null to unpause.

**Comment by SGrondin** [comment]
You're right! That's the way to do it.

**Comment by darky** [comment]
@SGrondin, can you please write example. How to properly change reservoir to 0, wait all running jobs and then change reservoir back to null? Or maybe better to implement `pause`, `resume` sugar over it :)

**Comment by darky** [comment]
This also should support clustering :)

**Comment by ducttapedev** [comment]
> You're right! That's the way to do it.

Sorry to grave dig, but I don't see any way to set the reservoir to 0 to pause the queue as @rlayne stated. Specifically, I'm trying to pause the queue for a set amount of time when I encounter a 429 error.

Right now the only ways I know how to accomplish this is by using a bottleneck factory and then stopping the active bottleneck when I want to pause, and the next time a bottleneck is requested it creates a new one with the same parameters. Or, queuing a bunch of higher priority jobs until the bottleneck capacity is maxed out, and then having those jobs sleep until the desired pause time has elapsed. Both seem very hacky.
