### ISSUE TITLE
runing function on event event only once

### ISSUE THREAD

**Issue by dkuida** [SGrondin/bottleneck#38]
Hi
I use the lib to do some throttling, and use 'empty' event to know when can I can put some cool down and retry the procedure.

I tried the `once()` instead of `on()`, but it is not supported. also tried to use the return value form `limiter.on()` but thats the limiter instance.

is there a way to fire the event only once ?

**Comment by SGrondin** [comment]
Hi, at the moment you can use the [reservoir](https://github.com/SGrondin/bottleneck#changereservoir-incrementreservoir) feature. The 'once' feature will be added in a future version.

**Comment by dkuida** [comment]
thanks!
