### ISSUE TITLE
How to cluster

### ISSUE THREAD

**Issue by weeco** [SGrondin/bottleneck#39]
Hello,
I read that this has been requested in the past and after a very long research I wasn't able to find a rate limiting library backed by redis which would also contain all the features I need, so somehow I am still stuck with bottleneck.

Literally every express project I wrote in the past required clustering. It's a pitty that bottleneck doesn't really support it. Every time I scale my application (up- or down) I am forced to adapt the amount of available requests for my limiters for each instance. Since the available requests usually don't change with my number of instances (because I am using external API services) this is very annoying.

Do you have any recommendations what I could do to solve this? Do you maybe intend to implement cluster support in a major update?

**Comment by TheGame2500** [comment]
@weeco Hi there! Take a look at https://github.com/SGrondin/bottleneck/issues/30 . Might help you to roll out your own fork, or wait until @SGrondin rolls out the changes there.

**Comment by SGrondin** [comment]
Yup. I'm working on a v2.0 right now.

**Comment by TheGame2500** [comment]
@SGrondin let me know if you need any help.

**Comment by SGrondin** [comment]
I'm closing this in favor of #30 . @weeco @TheGame2500 your input is appreciated in that other issue. v2.0 is getting a lot closer.
