### ISSUE TITLE
Provide a no-callback alternative to `submit`?

### ISSUE THREAD

**Issue by chocolateboy** [SGrondin/bottleneck#4]
Thanks for this. It seems to be perfect (for my simple use case) apart from this wart:

> If a callback isn't necessary, you must pass null or an empty function instead. It will not work if you forget to do this.

IMO, this is ugly. It pretty much requires that trailing parameter to be commented/explained away. And I'm not sure how to explain it, since the documentation itself doesn't explain it :-) How about adding a method which doesn't require a callback e.g. `schedule` i.e. allow:

```
limiter.submit(fn, null);
```

to be written as:

```javascript
limiter.schedule(fn);
```

**Comment by SGrondin** [comment]
That's a good idea! It'll make the library and the docs simpler and easier to understand. I'll implement it today or tomorrow. Thanks for your feedback.

**Comment by taoeffect** [comment]
@chocolateboy @SGrondin edited his response (if you're only checking email).

**Comment by chocolateboy** [comment]
@taoeffect Thanks.

@SGrondin If the purpose of the callback is to signal to bottleneck that the function is complete, I would expect bottleneck to supply the callback rather than the user, like the `done` callback in [mocha](http://mochajs.org/) e.g.:

```javascript
function fn (done, url) {
    http.get(url, (error, response) => {
        console.log(response.body);
        done();
    });
}

limiter.submit(fn, url);
```

In my use case the functions are [async](https://github.com/tc39/ecmascript-asyncawait) (ES7) and return a promise immediately e.g. (ES6):

```javascript
function fn (url) {
    return http.get(url).then(response => console.log(response.body));
}

limiter.schedule(fn, url);
```

Again, it might be worth taking a look at mocha, since it knows how to handle promises (as of [1.18.0](http://paulsalaets.com/testing-with-promises-in-mocha/)): http://mochajs.org/#asynchronous-code

**Comment by SGrondin** [comment]
I've been thinking about this a lot in the last few days and I think the best approach is to create a `submitPromise` which will be promise-aware. That should retain the minimalism of both the code (less than 100 lines) and API while making the library more powerful. I can't give a time estimate, but I hope to get it done soon.

**Comment by chocolateboy** [comment]
Sounds reasonable.

**Comment by SGrondin** [comment]
I've been working on this.

Instead of
```javascript
function fn (url) {
    return http.get(url).then(response => console.log(response.body));
}

limiter.schedule(fn, url);
```

Wouldn't it be simpler to just do
```javascript
limiter.submitPromise(promise).then(response => console.log(response.body));
```

Basically instead of passing a function (with arguments to be applied) that returns a promise, just pass a promise. Thoughts?

**Comment by SGrondin** [comment]
Actually, the approach I suggested in the previous post will rate limit the `then`/`catch` part, but not the executor (the promise's constructor).

I think most people will want to put their logic to be throttled in the executor instead of in a `then` block, so the function that returns a promise approach seems like the right one.

I've got the code working, we just need to iron out that detail and it should be good to go. I plan on pushing it to a separate branch to let @chocolateboy and @taoeffect test it and comment on it if they want to before I publish to NPM.

**Comment by SGrondin** [comment]
I just published v1.8.0 with `schedule`. It works like this:

```js
var fn = function(url) {
	return new Promise(function(resolve, reject) {
		setTimeout(function() {
			resolve(url)
		}, 200)
	})
}

limiter.schedule(fn, "google.com")
.then(function(url) {
	console.log("It worked", url)
})
.catch(function(err) {
	console.log("It failed", err)
})
```

It prints "It worked google.com".

**Comment by chocolateboy** [comment]
Thanks. I'll give it a go.

**Comment by chocolateboy** [comment]
The new documentation looks fine to me.

It would be nice if `schedule` used [bluebird](https://github.com/petkaantonov/bluebird) promises, [if available](https://www.npmjs.com/package/native-or-bluebird): native promises (in Node) [silently ignore unhandled rejections](http://jamesknelson.com/are-es6-promises-swallowing-your-errors/). I'm happy to submit a PR, but the gist of it is:

##### Bottleneck.coffee

```javascript
Promise = require 'native-or-bluebird'

class Bottleneck
    # ...
    new Promise (resolve, reject) =>
    # ...
end
```

Apart from that nice-to-have, the latest release does just what I need and I haven't encountered any issues. :+1:

**Comment by SGrondin** [comment]
Done in 1.8.1

**Comment by chocolateboy** [comment]
Thanks!
