### ISSUE TITLE
Task weight

### ISSUE THREAD

**Issue by TheGame2500** [SGrondin/bottleneck#40]
Working with Facebook's Graph API, I stumbled upon a neat 'batch request' feature which basically does what it says and allows you to bundle multiple requests into one. Unfortunately, I'm not sure how not to go over API limits using Bottleneck, since a batch request is counted as all the requests bundled in it. Is there a way to do this? If not, can we have a new feature where we can attribute weights to tasks ? (e.g. tell this library `this task is worth 5 tasks`)

**Comment by TheGame2500** [comment]
Note: In case this doesn't get implemented, for future seekers of batch limitation, I'm currently attempting a hack which works poorly. I'm passing the limiter as an argument to the function and do

```javascript
		// flood queue with fake batch.length number of jobs so that we don't overpass rate limit :/
		for (let i=0 ; i < params.batch.length; i++) {
			queue.schedule(()=>new Promise(yay=>yay()));
		}
```

**Comment by SGrondin** [comment]
Your temporary hack isn't a bad idea, but you must make sure that those empty promises
- are added immediately before the real call
- are resolved as soon as the real call is resolved or rejected

If I can add this into v2 without too much work it'll be part of v2.0, otherwise it'll be in v2.1.

**Comment by TheGame2500** [comment]
@SGrondin thanks for the tip. Any ETA for v2?

**Comment by TheGame2500** [comment]
@SGrondin I think the hack doesn't work (might be working OK, but can't really tell because Facebook's docs on rate limiting are lacking when it comes to Dev mode apps), so if you give me some instructions on how to set this repo up for development, or make a branch for v2/v2.1 I could submit a pull request for this since I'm in a bit of a rush.

**Comment by SGrondin** [comment]
I'm still just trying out ideas and designing before I write any code, so it'll be 2-4 weeks. Have you tried using the "reservoir" feature? you could manually increment and decrement it to achieve what you're looking for. Make sure to propagate those values over Redis if you're using that.. it's not easy to get it right.

**Comment by TheGame2500** [comment]
@SGrondin yes, I did, but then I realised that I didn't hack it together to work over redis and just went for the flood hack. I'd love to work on this (it's one of my favourite npm packs), so if you want to get in touch about it, PM me some contact detail (not sure that works over github) and a good time to get in touch.

**Comment by SGrondin** [comment]
Add an email address to your public GitHub profile! :)

**Comment by TheGame2500** [comment]
@SGrondin fair point ! 🤣 Done!

**Comment by SGrondin** [comment]
This has been implemented in v2, I'll let you know when it's released.

**Comment by SGrondin** [comment]
Version 2 has been released, please give it a try. Your feedback is welcome and appreciated!
