### ISSUE TITLE
More fleshed out errors

### ISSUE THREAD

**Issue by chrisbeard** [SGrondin/bottleneck#42]
When using promises, generic Errors are not super helpful.

Based on the current implementation of schedule for instance, it's not easy to tell if you're dealing with a rejection due to bottleneck's queue filling up or if your promise itself failed.

There are a few ways this could be addressed, I think. One is to set a `code` property a la [node.js errors](https://nodejs.org/api/errors.html#errors_system_errors), which should be sufficient. Another would be to use custom error types.

Thoughts?

**Comment by SGrondin** [comment]
The rewrite I'm working on features better errors. At the moment the code tries to pass back the error it got from the original callback/promise failure, but you're right that it's hard to tell them apart from Bottleneck's own errors. If Bottleneck generated its own `BottleneckError` it'd be a lot easier. I'm quite swamped at the moment, but I expect to have v2.0 ready in November.

**Comment by chrisbeard** [comment]
Awesome, thanks. Looking forward to it.

**Comment by SGrondin** [comment]
This has been implemented in master, I'll let you know when v2.0 is released.

**Comment by SGrondin** [comment]
Version 2 has been released, please give it a try. Your feedback is welcome and appreciated!
