### ISSUE TITLE
Typescript unable to compile using import syntax

### ISSUE THREAD

**Issue by bressain** [SGrondin/bottleneck#43]
Probably a question for @alexperovich, when importing bottleneck in a Typescript environment, I get compilation errors.

I'm importing like so:
```
import Bottleneck from 'bottleneck'
```
then using it:
```
const limiter = new Bottleneck(10)
```

When doing a compilation I get an error like:
```
TSError: ⨯ Unable to compile TypeScript
... File '.../node_modules/bottleneck/bottleneck.d.ts' is not a module.
```

My tsconfig.json looks like:
```
{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "scripthost", "es2017"],
    "outDir": "./build/",
    "noImplicitAny": true,
    "noUnusedParameters": true,
    "noUnusedLocals": true,
    "module": "commonjs",
    "target": "es6",
    "sourceMap": true,
    "inlineSources": true
  },
  "include": [
    "./**/*.ts"
  ],
  "exclude": [
    "node_modules",
    "ts-node"
  ]
}
```

I suspect that I'm doing something wrong here but this is a mature code base and haven't run into this with other packages. Any ideas?

**Comment by alexperovich** [comment]
What version of typescript are you using?
This
```typescript
import Bottleneck from "bottleneck";
var b = new Bottleneck();
b.changePenalty(1);
```
just compiled with typescript 2.6.2 and bottleneck 1.16.0 using your tsconfig and it I get no error.

**Comment by bressain** [comment]
2.6.2... You're right. I must apologize, upon further inspection, this appears to be an issue with ts-node. Thanks for taking the time to look into this. I'll go ahead and close the issue.

**Comment by SGrondin** [comment]
@alexperovich After many, many hours of development, I've released the [first beta version for the upcoming v2](https://github.com/SGrondin/bottleneck/tree/version-2), and there are several changes to the TS type definitions that I do not feel confident doing myself. Would you be able to help?

**Comment by alexperovich** [comment]
Sorry for the delay in responding, I have been on vacation for the holidays. It looks like you have things in hand. Was there something specific you were concerned about?

**Comment by SGrondin** [comment]
Thanks for the response, I was concerned about my lack of knowledge of TS and the ecosystem, but I figured it out. 😄
