### ISSUE TITLE
Issue when running on Node 6

### ISSUE THREAD

**Issue by cazzer** [SGrondin/bottleneck#47]
Currently using `bottleneck@2.0.1` and `node@6.10.3` and getting the following issue...
```
~/node_modules/bottleneck/lib/Bottleneck.js:73
      async disconnect(flush = true) {
            ^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (~/node_modules/bottleneck/lib/index.js:3:20)
    at Object.<anonymous> (~/node_modules/bottleneck/lib/index.js:5:4)
```

Should I expect this module to export logic that can run in my environment, or should I tell `babel` to have at it? Here's my `.babelrc` for the curious:
```json
{
    "presets": [[
        "env", {
          "targets": {
            "node": "6.10"
          }
        }
    ]],
    "plugins": [
      ["transform-object-rest-spread", {
        "useBuiltIns": true
      }]
    ]
}
```

**Comment by cazzer** [comment]
As a workaround, I am currently using `bottleneck@1.16.0`.

**Comment by SGrondin** [comment]
Bottleneck v2 uses async/await, which was introduced in Node 7.6 and is part of the latest LTS version, Node 8.

Feel free to let Babel have at it, I'll update the Readme to make it clearer that Bottleneck v2 uses modern JavaScript features.

Bottleneck v1 is still supported and will run on any Node version.

**Comment by SGrondin** [comment]
Since this issue is getting views and +1's, I'm now looking into adding a `package.json` `"engines"` minimum version for Node or something similar for Babel.

**Comment by SGrondin** [comment]
@cazzer  @toddb @deerawan The upcoming version `2.2.0` will be released this week. It runs Babel to precompile this library to be Node v6 compatible.

I realize at this point that it was a mistake to expect users to run an up-to-date version of Node or to be able to run Babel themselves. Bottleneck has always been a project that you can use out of the box, so `2.2.0` fixes that issue.

**Comment by cazzer** [comment]
Thanks for the support, @SGrondin! Some services, like AWS Lambda, still live in a `node@6` world which is probably where most of the issues come from.

**Comment by toddb** [comment]
+1

**Comment by SGrondin** [comment]
`2.2.0` is now available and works with Node v6. Enjoy!
