### ISSUE TITLE
highWater value 0 is not effective anymore

### ISSUE THREAD

**Issue by fkhachatrian** [SGrondin/bottleneck#48]
In earlier releases, setting highWater param to 0, ensured that the queue is not used. Together with OVERFLOW strategy this helped to make sure that submitted requests are all discarded, if there is a running request. In the last version this is not working anymore.

**Comment by SGrondin** [comment]
Hi,

Are your requests synchronous? Could you provide some code or pseudocode?

In v2, submitting requests is asynchronous, so it's possible that your requests have completed before Bottleneck has had a chance to attempt queueing up the next one.

Example assuming the requests are queued up in a simple loop:
```
- Request 1 is submitted and asks for how to proceed (execute, queue or drop)
- Request 1 begins executing, since nothing is running
- Request 2 is submitted and asks for how to proceed
- Request 1 immediately finishes
- Request 2 is told to be executed, since nothing is running
- Request 3 is submitted and asks for how to proceed
- Request 2 immediately finishes
etc...
```

I'll be able to understand exactly what is happening if you could provide me with the [`debug` event output](https://github.com/SGrondin/bottleneck#debugging-your-application).

Thanks for the bug report

**Comment by SGrondin** [comment]
Here's what I mean:
```js
const Bottleneck = require('bottleneck')

const limiter = new Bottleneck({
  maxConcurrent: 1,
  highWater: 0,
  strategy: Bottleneck.strategy.OVERFLOW
})

const syncJob = function (i) {
  console.log('Done (sync)', i)
  return Promise.resolve()
}

const asyncJob = function (i) {
  return new Promise(function (resolve, reject) {
    setTimeout(function () {
      console.log('Done (async)', i)
      return Promise.resolve()
    }, 0)
  })
}
```
If I add 5 **Synchronous** jobs to the limiter
```js
for (var i = 1; i <= 5; i++) {

  limiter.schedule(syncJob, i)
  .catch(function (err) {
    console.log(err.message)
  })

}
```
It outputs:
```
Done 1
This job has been dropped by Bottleneck
Done 3
This job has been dropped by Bottleneck
Done 5
```
But if I add 5 **Asynchronous** jobs to the limiter
```js
for (var i = 1; i <= 5; i++) {

  limiter.schedule(asyncJob, i)
  .catch(function (err) {
    console.log(err.message)
  })

}
```
It outputs:
```
Done 1
This job has been dropped by Bottleneck
This job has been dropped by Bottleneck
This job has been dropped by Bottleneck
This job has been dropped by Bottleneck
```
This is working as expected. Synchronous jobs are **instantaneous** in the eyes of an event loop system like Nodejs. Wrap them in a `setTimeout( ... , 0)` to make them asynchronous.

Feel free to reopen this issue if you can provide a code example of the problem you're describing.
