### ISSUE TITLE
Retries after a certain time.

### ISSUE THREAD

**Issue by ajagnanan** [SGrondin/bottleneck#52]
Hi, is it possible to do a backoff policy with retry capability? I'm using the 'function wrap' option and was looking for a way to retry a request if the throttling exception occurs, but wait a few seconds before making the follow up request. Thanks

**Comment by SGrondin** [comment]
It's not currently built-in, but you can use the `dropped` event to try again after a timeout.

Here's what it would look like. I didn't test this code, I only provide it as a starting point:
```js
let wait = 10;

limiter.on('dropped', function (dropped) {
  setTimeout(function () {
    myWrappedFunction.apply({}, dropped.args);
  }, wait);
  wait = wait * 2;
});
```

This might be a cool addition to Bottleneck, I'll keep thinking about it.

**Comment by colinskow** [comment]
I would like the ability to pause and entire group for a specified period of time if a throttling exception occurs. Instead of just retrying one job, I want to pause everything to give my quota time to recuperate.

**Comment by SGrondin** [comment]
>I would like the ability to pause and entire group for a specified period of time if a throttling exception occurs. Instead of just retrying one job, I want to pause everything to give my quota time to recuperate.

It's not possible for Bottleneck to know whether your job failed due to a throttling error (HTTP Error 429) or any other type of error, exception, etc.

I'm thinking it could be nice to have a `limiter.pauseFor(ms)` method you could call after your code catches a "throttling exception".

Thoughts?

**Comment by SGrondin** [comment]
This was finally added to Bottleneck v2.15.0 🎉 

See [Retries](https://github.com/SGrondin/bottleneck#retries).
