### ISSUE TITLE
Bottleneck v2.x seems to require redis, regardless of new Clustering setting?

### ISSUE THREAD

**Issue by TehCrucible** [SGrondin/bottleneck#53]
Maybe I'm doing something wrong, but I've just updated to v2 in my project and although I have no intention of using clustering, my build is failing with complaints of not being able to resolve redis from node_modules?

```
Error: ./node_modules/bottleneck/lib/RedisStorage.js
Module not found: Error: Can't resolve 'redis' in 'C:\Users\jamie\Projects\massblock-app\node_modules\bottleneck\lib'
resolve 'redis' in 'C:\Users\jamie\Projects\massblock-app\node_modules\bottleneck\lib'
  Parsed request is a module
  using description file: C:\Users\jamie\Projects\massblock-app\node_modules\bottleneck\package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\Users\jamie\Projects\massblock-app\node_modules\bottleneck\package.json (relative path: ./lib)
    resolve as module
      looking for modules in C:\Users\jamie\Projects\massblock-app\node_modules
        using description file: C:\Users\jamie\Projects\massblock-app\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\Users\jamie\Projects\massblock-app\package.json (relative path: ./node_modules)
          using description file: C:\Users\jamie\Projects\massblock-app\package.json (relative path: ./node_modules/redis)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\jamie\Projects\massblock-app\node_modules\redis doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\jamie\Projects\massblock-app\node_modules\redis.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\jamie\Projects\massblock-app\node_modules\redis.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\jamie\Projects\massblock-app\node_modules\redis.json doesn't exist
            as directory
              C:\Users\jamie\Projects\massblock-app\node_modules\redis doesn't exist
[C:\Users\jamie\Projects\massblock-app\node_modules\redis]
[C:\Users\jamie\Projects\massblock-app\node_modules\redis.ts]
[C:\Users\jamie\Projects\massblock-app\node_modules\redis.js]
[C:\Users\jamie\Projects\massblock-app\node_modules\redis.json]
[C:\Users\jamie\Projects\massblock-app\node_modules\redis]
 @ ./node_modules/bottleneck/lib/RedisStorage.js 77:14-30
 @ ./node_modules/bottleneck/lib/Bottleneck.js
 @ ./node_modules/bottleneck/lib/index.js
```

Any thoughts?

**Comment by TehCrucible** [comment]
Looking deeper, this might be a Typescript issue, importing into Angular.

**Comment by SGrondin** [comment]
Hi, this is definitely an issue with your build process.

The `redis` module is only imported within the `RedisStorage` constructor, [which means Bottleneck only attempts to `require` that module when Clustering is enabled](https://github.com/SGrondin/bottleneck/blob/bfc32f7aee01a234efe93e0f409047beffac98f5/src/RedisStorage.coffee#L54).

But I'm still pretty sure I know what issue you're running into with your build:
You need to tell whatever packaging tool you use to ignore the `redis` module. If you're using Browserify, you need to pass it the `-u redis` option. Packaging tools read the source code and find all the places where modules are required, then go read those modules and so on. Whichever packaging system you're using will definitely let you ignore certain modules.

**Comment by SGrondin** [comment]
Here's Bottleneck's own build script: https://github.com/SGrondin/bottleneck/blob/bfc32f7aee01a234efe93e0f409047beffac98f5/scripts/build.sh#L24

Bottleneck uses Browserify to build a frontend bundle to be used by browsers. Nodejs users still require() Bottleneck as usual.

**Comment by SGrondin** [comment]
The upcoming `2.2.0` release will be released this week. It contains a change that solves your issue without requiring you to ignore modules (as you should).

To be clear, it's *normal and expected* of you as an Angular/Webpack/Browserify/etc user to have to exclude modules sometimes, but if I, as a module author, can make your life easier without too much trouble, then I'll do it.

**Comment by SGrondin** [comment]
Version `2.2.0` has been released, which should eliminate this issue.

**Comment by TehCrucible** [comment]
Hey, thanks Simon. Apologies for not getting back to you on this one, I simply reverted to v1 at the time and didn't get a chance to revisit yet.

I have no doubt you are 100% right about the simple exclusion, but I appreciate your effort to update the package regardless. Looking forward to giving the new version a spin.

**Comment by SGrondin** [comment]
No worries! I hope v2 works great for you.

I was being extra clear in my previous message for those landing on this page from Googling a generic error like `Module not found: Error: Can't resolve 'redis'`.
