### ISSUE TITLE
Jobs processing order in cluster mode

### ISSUE THREAD

**Issue by Nemmo** [SGrondin/bottleneck#56]
Hi folks!

I have a problem with the clustering mode. As you can see at the screenshot jobs has been running 1st, 3rd, 2nd, 4th, but not in sequential order.
There are 2 node processes. Job working time is 1 second.

![image](https://user-images.githubusercontent.com/5058015/37552281-239eedb0-29dc-11e8-98e3-dd737aab2e4d.png)

**Comment by SGrondin** [comment]
Hey, can you show what settings you are using on your limiters? That way I can try to reproduce it.
Thank you

**Comment by SGrondin** [comment]
Also, are the 2 node processes running on the same computer or different ones? How much time apart are you scheduling those jobs? It's possible for the time on those 2 instances to be off by a few 100ms, or network latency to cause job 3 to be received by the Redis server before job 2.

**Comment by Nemmo** [comment]
I have 2 docker containers with node processes. That 4 jobs has been sent in less than 1 second (you can see it on the screenshot). Redis is also running inside a docker container. All containers are local (docker-compose)

```js
// limiter
const limiter = new Bottleneck({
  maxConcurrent: 2,
  datastore: 'redis',
  clearDatastore: false,
  clientOptions: { /* redis options */ },
})

// bottleneck function
fn(): Promise<void> {
  return new Promise<void>((resolve) => {
    setTimeout(() => {
      return resolve();
    }, 1000);
  });
}

// function call
await limiter.schedule(() => fn());
```

**Comment by SGrondin** [comment]
Thank you for the information. I'll be working on it this week. I'll keep you updated.

**Comment by SGrondin** [comment]
How are the jobs distributed? Is it
- Like this (A):
  - Node process 1: Job 1, Job 2
  - Node process 2: Job 3, Job 4
- Or like this (B):
  - Node process 1: Job 1, Job 3
  - Node process 2: Job 2, Job 4

From the Readme:
>Queued jobs are NOT stored on Redis. They are local to each limiter. Exiting the Node.js process will lose those jobs. This is because Bottleneck has no way to propagate the JS code to run a job across a different Node.js process than the one it originated on. Bottleneck doesn't keep track of the queue contents of the limiters on a cluster for performance and reliability reasons.

>Due to the above, functionality relying on the queue length happen purely locally:

>**Bottleneck guarantees that jobs will be run in the order they were queued on the same limiter. Another limiter on the cluster might run a job queued later before ours runs.**

>You must work around these limitations in your application code if they are an issue to you.

>The current design guarantees reliability and lets clients (limiters) come and go. Your application can scale up or down, and clients can be disconnected without issues.

Bottleneck guarantees that jobs are run in order **separately for each limiter**.

So for case A:
- Bottleneck guarantees:
  - job 1 will run before job 2
  - job 3 will run before job 4
- But anything else is possible, ex: job 3 or job 4 could run before job 2 or job 1, etc.

And for case B:
- Bottleneck guarantees:
  - job 1 will run before job 3
  - job 2 will run before job 4
- But anything else is possible, ex: job 2 or job 4 could run before job 3 or job 1, etc.

**Comment by Nemmo** [comment]
> Bottleneck guarantees that jobs are run in order separately for each limiter.

OK, got it. It does not matter in the most projects, I think.

But the order is critical for in my case. How can I reach this behavior? Could you give me a hint? Cause I didn't find any js/ts module (queue/mutex) that limits the number of requests per time to the external endpoint (in my case) totally in N separate node processes. And the main condition is to support horizontal scale. What do you think?

For example, when I have 3 node processes it must be only 5 requests per second to the external web service (endpoint).
