### ISSUE TITLE
Heads up: .on() no longer returns instance, breaking api

### ISSUE THREAD

**Issue by bkw** [SGrondin/bottleneck#59]
Just a quick heads up that somewhere between 2.1.0 and 2.2.1 the api was changed so that calls to `bottleneck.on()` no longer return the bottleneck instance and thus are no longer chainable.

Maybe not a biggie, but probably still worth a mention in the release notes since (for us) this was a breaking change and makes bottlenecks behavior now differ from node's `events.EventEmitter.on()`.

**Comment by SGrondin** [comment]
Thanks for the bug report, it will be fixed in 2.2.2

**Comment by SGrondin** [comment]
`2.2.2` has been released, which includes a fix for this issue. **Thank you** for the bug report!
