### ISSUE TITLE
problem using bottleneck

### ISSUE THREAD

**Issue by mike442144** [SGrondin/bottleneck#6]
I use `bottleneck` in my project and ran for half a month, got problems I had no idea.First I post an image.

![plot](https://cloud.githubusercontent.com/assets/1272762/10040856/16c3d4b4-6212-11e5-837f-ab4090e87d36.png)

In the plot, X is 50 time points, Y is time spent in second,rectangle is total time spent for each request, and diamond is bottleneck wait time. 

Rate limit I set is 3s. Obviously, we can see most points of the set are doing good, but 9~10 of them seems unreasonable that is very high in the imagae, Anyone who have same problem?

**Comment by SGrondin** [comment]
Hi @mike442144 

I'm not able to reproduce the problem, can you post a small code snippet?

**Comment by mike442144** [comment]
It's difficult to reproduce in short time.
Actually, this seems not seriously in my project, I can tolerate this.
thanks @SGrondin

**Comment by SGrondin** [comment]
No problem. Reopen the issue if you find a way to reproduce it easily. My guess is that you may have so many limiters (and they each have timers) that V8's scheduler gets less accurate.
