### ISSUE TITLE
Queued never returns a number > 0

### ISSUE THREAD

**Issue by krishangupta** [SGrondin/bottleneck#61]
If you queue up a bunch of jobs, then check the length (a few seconds later), you'll see it's still 0.

```

var Bottleneck = require('bottleneck')
var lt = Bottleneck.limiter({minTime: 1000})

for(let i=0; i<10; i++){
    lt.schedule(async ()=>{ return await sleep(10000); console.log('done') }) 
}

console.log(lt.queued())
```

Note: I do realize queued queued won't be immediately accurate. But ever if you wait a few seconds before running `console.log(lt.queued())`, it's still 0.

**Comment by SGrondin** [comment]
With `{minTime: 1000}` and no `maxConcurrent`, there is no reason to queue up your jobs since Bottleneck is able to tell **exactly** when each job will be executed, so it immediately schedules them in the future. If you want to force queueing to happen, you can set a `maxConcurrent` value.

**Comment by krishangupta** [comment]
@SGrondin thanks for the quick response! I've read the docs, but I don't think I really understand how Bottleneck works, or what the meaning of queued is here.

Let's say I put 1M jobs scheduled at the same time (with a 1 second minTime, no maxConcurrent). Would they all be executed immediately? Or would they be executed one per second over the next 1M seconds?

If it's the second, is there any way to check how many jobs Bottleneck is tracking at the moment?

**Comment by SGrondin** [comment]
>I had mistakenly thought that queued meant scheduled, but it seems there is a difference.

Indeed. As soon as Bottleneck is able to know exactly at what timestamp a job should run, it removes it from the queue and schedules it. So for a `{ minTime: 1000 }` with no `maxConcurrent`, Bottleneck knows that if you were to give it 5 jobs, they would run at `Now`, `Now+1000ms`, `Now+2000ms`. For example, if you have `maxConcurrent: 1` and there's currently a job running, Bottleneck doesn't know when that job will complete, so it cannot schedule the next one until then, so it remains in the queue.

I think you're right that Bottleneck needs to offer the user a way to tell how many are scheduled. I think your original assumption that `.queued()` should return the number of *non-executing jobs* is right. The Readme is misleading.

>Is there a way to know how many jobs are scheduled?

I plan on adding this feature to `v2.3.0`, but at the moment you can get that number by calling
```js
Object.keys(limiter._executing).length
```
**WARNING:** I cannot guarantee that this code will return the right result after `v2.3.0` is released!

Try running this example to see it in action:
```js
const Bottleneck = require('bottleneck')
const limiter = new Bottleneck({ minTime: 1000 })

const t0 = Date.now()
const print = (...args) => {
  console.log([(Date.now()-t0) + 'ms'].concat(args).join(' '))
}

const getScheduledCount = (limiter) => {
  return Object.keys(limiter._executing).length
}

limiter.schedule((i) => Promise.resolve(i), 1).then((x) => {print('Done:', x)})
limiter.schedule((i) => Promise.resolve(i), 2).then((x) => {print('Done:', x)})
limiter.schedule((i) => Promise.resolve(i), 3).then((x) => {print('Done:', x)})
limiter.schedule((i) => Promise.resolve(i), 4).then((x) => {print('Done:', x)})
limiter.schedule((i) => Promise.resolve(i), 5).then((x) => {print('Done:', x)})

setInterval(() => {
  print('Scheduled:', getScheduledCount(limiter))
}, 500)
```
```
10ms Done: 1
504ms Scheduled: 4
1007ms Scheduled: 4
1010ms Done: 2
1509ms Scheduled: 3
2009ms Scheduled: 2
2010ms Done: 3
2512ms Scheduled: 2
3009ms Done: 4
3012ms Scheduled: 1
3512ms Scheduled: 1
4007ms Done: 5
4014ms Scheduled: 0
4519ms Scheduled: 0
```

**Comment by SGrondin** [comment]
I've gotta warn you, the number you get back with that `getScheduledCount` function I gave you includes both the "running jobs" (the scheduled jobs) and the "executing jobs". Here's a preview of the Readme in v2.3.0 and the upcoming `.counts()` function:

### Jobs lifecycle

1. **Received**. You new job has been added to your limiter. Bottleneck needs to check whether it can be accepted into the queue, based on your `highWater` setting.
2. **Queued**. Bottleneck has accepted your job, but it can not tell at what exact timestamp it will run yet, because it is dependent on previous jobs.
3. **Running**. Your job is not in the queue anymore, it will be executed after a delay computed according to your `minTime` setting.
4. **Executing**. Your job is executing its code.

#### counts()

```js
const counts = limiter.counts();

console.log(count);
/*
{
  RECEIVED: 0,
  QUEUED: 0,
  RUNNING: 0,
  EXECUTING: 0
}
*/
```

**Comment by SGrondin** [comment]
`2.3.0` is now available. Let me know what you think!

**Comment by krishangupta** [comment]
Awesome thanks @SGrondin! I'll check it out in a few days.
