### ISSUE TITLE
Feature request: safe shutdown

### ISSUE THREAD

**Issue by rogierschouten** [SGrondin/bottleneck#63]
For all kinds of purposes I'd like to have a `stop()` method that:

1. Prevents new items from being queued (enqueueing should reject with an error given as argument to the stop method)
1. Waits for all running items to finish
1. Rejects all queued items with a predefined error (given as argument to the stop method)
1. Resolves when all that is done

This would allow disposing of my queue e.g. when the system is stopped in a controlled manner. 

Also very handy for ensuring everything stops when a unittest fails.

**Comment by SGrondin** [comment]
I like this idea a lot. I've been experimenting with different types of shutdowns and none met all needs. I'm going to combine your suggestions with the ones from #60. It will take an options object that will let you do exactly what you're describing above. Intentionally failing running jobs is another common use case that needs to be supported.

I should have a prototype for you shortly, would you be interested in trying it out and providing feedback before it is released?

**Comment by rogierschouten** [comment]
@SGrondin sure I would like to try it! Just let me know. 

The shutdown as I described it is quite common in a-synchronous systems. I use it a lot and it works well.

**Comment by rogierschouten** [comment]
I just realized that there may be cases where you'd want to run the queue empty, i.e. instead of step 3 one might want to just finish all queued items.  I guess that should be an option for the stop() method then.

**Comment by SGrondin** [comment]
Yup, that will bee an option.

**Comment by rogierschouten** [comment]
For my own planning, what is the status and planning for this issue?

**Comment by rogierschouten** [comment]
No I'm not at the moment

**Comment by SGrondin** [comment]
This took _a lot_ of work to get right, but I think the end result is a flexible and elegant solution that should meet most people's needs.

It will be released as v2.5.0 soon, but you can currently try it on this branch (fully tested!):
`npm install --save git://github.com/SGrondin/bottleneck.git#limiter-stop`

Use it like this:
```js
limiter.stop(options)
```
`stop()` takes an optional options object:
- `dropExisitingJobs` (boolean, default true). Drops everything that's not currently executing.
- `dropError` (Error object), error used to reject waiting jobs.
- `enqueueError` (Error object), error used reject jobs added after `stop()` has been called.

`stop()` returns a promise that resolves once all waiting jobs have been dropped (if using `dropExistingJobs`) and once all the executing jobs have completed.

Feedback would be greatly appreciated.

**Comment by SGrondin** [comment]
`v2.5.0` has been released with the new `stop()` method. 🎉 😄 Feedback is appreciated!

**Comment by rogierschouten** [comment]
Sorry I didn't have a look at it in time @SGrondin, I've been too busy lately. Thanks for your efforts and it looks good!

**Comment by SGrondin** [comment]
No worries! If you end up trying it out, I'd really appreciate to hear what you think of it, even if it takes months. Whether it's good or bad, I take it into account.

**Comment by RickVazquez** [comment]
I'm getting an error when running

`  this.limiter.stop({}).then(() => {
            console.log("Shutdown completed!")
        }).catch((error) => {
            console.log("ERROR", error)
        });
`

![Screen Shot 2019-10-03 at 11 55 10](https://user-images.githubusercontent.com/38468346/66121305-c6a46200-e5d4-11e9-955a-1d1e1e8c754e.png)

**Comment by SGrondin** [comment]
Look at the docs for stop: https://github.com/SGrondin/bottleneck#stop

In the table, you'll see that if `dropWaitingJobs` is `true`, then all waiting jobs will be dropped with the message `This limiter has been stopped.`

If you want to wait for the jobs to complete, then pass `dropWaitingJobs: false` in the options object here: `limiter.stop(options)`
