### ISSUE TITLE
Feature request: Ignore jobs with same ids

### ISSUE THREAD

**Issue by mendeljacks** [SGrondin/bottleneck#68]
At the moment when jobs are created with identical ids, an error is thrown which stops node js.
BottleneckError: A job with the same id already exists.

I would like bottleneck to be able to continue operation after receiving the job and prevent the job from adding to the queue so normal operation can resume and job will not be fulfilled more than once for no reason.

**Comment by SGrondin** [comment]
Easy, simple and useful, I like it.

**Comment by SGrondin** [comment]
In the next version of Bottleneck, jobs with the same ID as a previous job will be rejected by Bottleneck without being executed. You can then choose to ignore the error. It won't throw an exception anymore. Does this meet your needs?

Example (next version, v2.4.0):
```js
limiter.schedule({ id: "blah" }, job)
.then((result) => {
  // success
})
.catch((error) => {
  if (error.message.indexOf('A job with the same id already exists') === 0) {
    // ignore
  } else {
    // handle other errors
  }
})
```

Another thing you can do is check if a job already exists before submitting it again.

Example (current version, v2.3.0):
```js
if (limiter.jobStatus("blah") == null) {
  limiter.schedule({ id: "blah" }, job)
}
```

**Comment by SGrondin** [comment]
v2.4.0 has been released
