### ISSUE TITLE
Question : is it possible to pause task execution temporarily?

### ISSUE THREAD

**Issue by slumbi** [SGrondin/bottleneck#71]
Hi !

I would like to pause task execution by for example changing maxConcurrent to 0, and resume it when value becomes non-zero. During this time I guess the submit calls need to block somehow.

A quick hack could be to increase minTime , but it means resuming task execution would be complicated.
Thanks.

**Comment by SGrondin** [comment]
Hi!

Very good question. The best way is to set `reservoir` to `0`. You can unpause it by setting `reservoir` back to `null`.

**Comment by slumbi** [comment]
Thank you, works perfectly.
