### ISSUE TITLE
OOM when using Redis clustering

### ISSUE THREAD

**Issue by cisox** [SGrondin/bottleneck#73]
I'm using Bottleneck pretty extensively across three limiter ids that sync from different data sources. I'm using it for frequent data syncing across multiple scripts that sometimes run concurrently. Everything is working fine on my local environment where the load is low but when running on production, I'm getting these out-of-memory errors. Any suggestions on how to solve this issue other than bumping up max memory on the redis server?

```
limiter-id { ReplyError: ERR Error running script (call to f_081727f152360d42d3fac68bacc404106bcfa968): @user_script:87: @user_script: 87: -OOM command not allowed when used memory > 'maxmemory'.   
    at parseError (/var/www/site/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/var/www/site/node_modules/redis-parser/lib/parser.js:303:14)
  command: 'EVALSHA',
  args: 
   [ '081727f152360d42d3fac68bacc404106bcfa968',
     3,
     'b_limiter-id_settings',
     'b_limiter-id_running',
     'b_limiter-id_executing',
     'iknao23dejl',
     '1',
     '60000',
     '1530868561182' ],
  code: 'ERR' }
```

**Comment by SGrondin** [comment]
Hi, thanks for using Bottleneck.

Version `2.5.1` was released a few days ago and it fixes a memory leak issue. If you're not already using `2.5.1`, upgrading to it will most likely solve your issue.

However, if you're still seeing this error on `2.5.1`, I need to ask you a few questions to debug the issue:
- What is your Bottleneck config?
- Are you using Groups?
- Are you using [JobOptions](https://github.com/SGrondin/bottleneck/#job-options), if so, what are they?
- Can you provide a rough estimate to the number of requests/minute are going to the Redis Cluster?

Thank you!

**Comment by cisox** [comment]
I've upgraded to 2.5.1 but also upgraded the redis server. I can't reproduce the issue at the moment but I'll re-open this if I do later.
