### ISSUE TITLE
Is there any way to find running job id or index?

### ISSUE THREAD

**Issue by gsmtamil** [SGrondin/bottleneck#76]
In cluster mode, if I gave max concurrent is 1 and minTime is 10000
I am assigning 5 to 10 job randomly with the same id.

if I assign 5 job with the same id, it will execute one by one based on minTime:
is there any way to find which job (id or index) is running currently inside schedule function?

**Comment by SGrondin** [comment]
You can call `limiter. jobStatus(id)` and it will tell you if it's running. You can also call `limiter.counts()` and it will show you how many jobs are running. But right now there's no way to get a list of ids that are running. It's a good idea, I'll add it to Bottleneck.

**Comment by SGrondin** [comment]
Added to [v2.9.0](https://github.com/SGrondin/bottleneck/releases/tag/v2.9.0)
