### ISSUE TITLE
Possibly incorrect typings definition for `reservoir`

### ISSUE THREAD

**Issue by acheronfail** [SGrondin/bottleneck#79]
When using this library with TypeScript one can't set `reservoir` to `null` since the type is only an optional `number`.

This is an issue if there's ever a need to pause the limiter. As discussed in #71, the recommended way of doing this is by:

```typescript
// Pause the limiter
limiter.updateSettings({ reservoir: 0 });

// ...

// Sometime later, unpause the limiter
limiter.updateSettings({ reservoir: null }); // <--- this won't compile
```

At the moment a workaround is by passing `Infinity`:

```typescript
limiter.updateSettings({ reservoir: Infinity });
```

Although, this feels somewhat hacky. Should this be the way to pause/unpause the limiter when using TypeScript?

Otherwise, updating the Typings Definition with something along these lines should also solve the problem:

```typescript
{
	reservoir: number | null | undefined
}
```

**Comment by SGrondin** [comment]
v2.7.2 has been released, it fixes 6 nullable options that weren't properly marked as nullable. I've also added an example to the typings test.
