### ISSUE TITLE
React build fails on minifying parser.js

### ISSUE THREAD

**Issue by UpsideDownRide** [SGrondin/bottleneck#81]
Dev server runs smoothly however when attempting to build I run into following: 

    > react-app-rewired build
    
    Creating an optimized production build...
    Failed to compile.
    
    Failed to minify the code from this file:

            ./node_modules/bottleneck/lib/parser.js:5

    Read more here: http://bit.ly/2tRViJ9

    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! cryptofolio@0.1.0 build: `react-app-rewired build`
    npm ERR! Exit status 1

I'm a noob when it comes to webpack so I'm not sure how to proceed with debugging this other than trying to google-fu this. Any help would be very appreciated.

**Comment by UpsideDownRide** [comment]
Solved with manually transpiling to es2015 with following .babelrc:

    {
      "presets": [
        ["env"]
        ]
    }

**Comment by SGrondin** [comment]
Glad to hear you found a solution. I've been thinking about targeting `env` by default instead of [6.0](https://github.com/SGrondin/bottleneck/blob/master/.babelrc)
