### ISSUE TITLE
priority not working

### ISSUE THREAD

**Issue by VarPDev** [SGrondin/bottleneck#83]
I have a queue with 100 promises with priority 5 and when schedule a new promise with priority 1 it waiting all the other 100 call

**Comment by SGrondin** [comment]
What options are you using? You might need to set a `maxConcurrent` value for priorities to work with your options.

**Comment by SGrondin** [comment]
Priorities essentially allow some jobs to skip ahead of other jobs in the queue. Without a `maxConcurrent` value (and/or a `reservoir`), jobs only stay in the queue for a very brief instant before being scheduled for execution at a later time.
