### ISSUE TITLE
Is there option to send redis connection object to limiter 

### ISSUE THREAD

**Issue by gsmtamil** [SGrondin/bottleneck#84]
Is there any option to send Redis connection object to createlimiter , if not can you add this

Why do I need this:
 In my scenario, I need to create 200 to 500 limiter in a one second with different ids each limiter will have 5 to 10 jobs but it will execute only one concurrent job in each limiter at a time.
 While creating each limiter I need to send Redis config. I guess you need to create a Redis connection for each limiter. actually, already  I have the Redis connection object, why don't I reuse this Redis connection.

Note: If you are using Redis pub-sub concepts here, we need to send two different Redis connection object.(#82 )
  
Expected options like this:
```js
const createLimiter = ({ id, maxConcurrent = 1, minTime = 500, clearDatastore = false ,redisConnection}) => {
  return new Bottleneck({
    maxConcurrent,
    minTime,
    id,
    datastore: "redis",
    datastoreConnection:redisConnection,
    clearDatastore,
    timeout: 300000, //
  });
};
```

**Comment by SGrondin** [comment]
Do all the same limiters have the same `maxConcurrent` and `minTime` settings?

If yes, then you should use a Group. All the limiters within a Group share the same Redis connection.

If no, it's an interesting feature that I think could make an interesting addition to Bottleneck.

**Comment by gsmtamil** [comment]
Thank you for your suggestion, Right now, I can use Group almost  90 % of my work.
But in my work, we have the plan to change dynamically `maxConcurrent` based on the situation.
I will keep watching this feature.

Thankyou Bottleneck.

**Comment by SGrondin** [comment]
You could use a Group and do this:
```js
const group = new Bottleneck.Group({
  maxConcurrent: 1,
  minTime: 500,
  datastore: "redis",
  clearDatastore: false,
  timeout: 300000
});

const createLimiter = ({ id, maxConcurrent = 1 }) => {
  const limiter = group.key(id);
  if (maxConcurrent !== 1) {
    limiter.updateSettings({ maxConcurrent });
  }
  return limiter;
};
```

**Comment by gsmtamil** [comment]
`   
const group = new Bottleneck.Group({
  maxConcurrent: 1,
  minTime: 500,
  datastore: "redis",
  clearDatastore: false,
  timeout: 300000
});
`
`
const createLimiter = ({ id }) => {
  const limiter = group.key(id);
  return limiter;
};
`
`
const testGroup = testId => {
  const limit = createLimiter({ id: testId });
  limit
    .ready()
    .then(() => {
      limit
        .schedule(async () => {
          await sleep(2000);
          return "done -- " + testId;
        })
        .then(result => {
          console.log(result);
        })
        .catch(error => {
          console.error(error);
        });
    })
    .catch(error => {
      console.error(error);
    });
};
`
//id 1
testGroup("ABC123");
testGroup("ABC123");
testGroup("ABC123");
testGroup("ABC123");

//id 2
testGroup("ABC321");
testGroup("ABC321");
testGroup("ABC321");
testGroup("ABC321"); ` 

Is these two keys `(ABC123, ABC321 )` are taking a single Redis Connection?

**Comment by gsmtamil** [comment]
Based on #76 
In Cluster mode, if you have given like this `limiter.completedJobs()` and `limiter.totalAssignedJobs`
I will dynamically change `maxConcurrent` 

```
limiter.schedule(async () => {
  const currentJobIndex = limiter.completedJobs();
  if (currentJobIndex == 0) {
    //step 1 driver selection completed
    emiter.emit("success", "firstDriverSelectionCompleted");
  } else if (currentJobIndex == 1) {
    //step 2 driver selection completed
    emiter.emit("success", "secondtDriverSelectionCompleted");
  } else if (currentJobIndex == 2) {
    //step 3 driver selection completed
    emiter.emit("success", "thirdDriverSelectionCompleted");
  } else if (currentJobIndex == 3) {
    limiter.updateSettings({ maxConcurrent: limiter.totalAssignedJobs - (currentJobIndex + 1) });
    emiter.emit("error", "job assigned to another driver");
  } else {
   emiter.emit("error", "job assigned to another driver");
  }
  return "done -- " + testId;
});
```

**Comment by SGrondin** [comment]
> Is these two keys (ABC123, ABC321 ) are taking a single Redis Connection?

Yes

Remember to also catch errors on the group and limiters:
```js
group.on("error", (err) => {
  // do something
});
limiter.on("error", (err) => {
  // do something
});
```

In `v2.9.0` you don't need to wait for `ready()`. Also, putting promises inside of promises isn't good practice in JavaScript. Do this instead:
```js
const testGroup = testId => {
  const limit = createLimiter({ id: testId });
  limit
    .schedule(async () => {
      await sleep(2000);
      return "done -- " + testId;
    })
    .then(result => {
      console.log(result);
    })
    .catch(error => {
      console.error(error);
    });
};
```

>For this can I use const counts = limiter.counts(); is this will work in cluster mode ?

No, `limiter.counts()` only returns the information for this limiter, not the whole Cluster. Only `limiter.running()` works on the whole Cluster.

You could keep track of this information in your database or you could use the new `publish()` method to let the whole Cluster know when a job is done.

I can't add a method that works like `counts()` and works on the whole Cluster, but I'm thinking about adding a method that returns the number of completed jobs in the Cluster.

**Comment by SGrondin** [comment]
I'm closing this in favor of #86 

Soon it will be possible to pass existing connections to new limiters and groups.

**Comment by SGrondin** [comment]
I forgot to mention, v2.10.0 added a new `done()` method, it returns the **total weight** of all jobs that have reached the DONE state **in the Cluster**.
