### ISSUE TITLE
Do not drop jobs

### ISSUE THREAD

**Issue by cesarvarela** [SGrondin/bottleneck#85]
Is it possible to do not drop jobs and just queue them forever (until they are eventually executed)?

Just read the definition of every strategy and it's not clear if any of them achieves that.

thanks

**Comment by cesarvarela** [comment]
cool, so if I want to run jobs 250/s per second, will this work:

```
const limiter = new Bottleneck({
  maxConcurrent: 250,
  minTime: 1000/250
});
```

**Comment by SGrondin** [comment]
Yup! 😄

**Comment by cesarvarela** [comment]
Thanks' we'll give it a try!

**Comment by SGrondin** [comment]
Awesome, let me know if you run into any issues 😄
