### ISSUE TITLE
Require a new option to get all group keys

### ISSUE THREAD

**Issue by gsmtamil** [SGrondin/bottleneck#97]
keys() Will Returns an array containing all the keys in the specified Group.
limiters() Will Return all the limiters and key in the specified group. 

But We need an option to get all the limiters and all the groups, which is now available in Redis. It needs to return all the values in cluster level. 

getAllKeys();    
getAllLimiters();

**Comment by SGrondin** [comment]
Agreed. I'm working on some major Clustering improvements for 2.14.0. It will include this feature, called `group.clusterKeys()`.

**Comment by SGrondin** [comment]
I've just released 2.14.0. You can now use`group.clusterKeys()`. I did not add `group.clusterLimiters()` because it could create a lot of load and if you need it you can just create limiters from the keys returned by `group.clusterKeys()`.

Please let me know if you run into any issues.
