### ISSUE TITLE
user_script - attempt to concatenate local 'final_capacity' (a nil value)

### ISSUE THREAD

**Issue by treyduffy** [SGrondin/bottleneck#98]
I'm getting an error when using redis (Elasticache)

`ReplyError: ERR Error running script (call to f_e275b1feeacbf5bcf4eb2e4a524a32d702c22ce4): @user_script:105: user_script:105: attempt to concatenate local 'final_capacity' (a nil value)`

Any direction would be great.

Setup: 

```
  redisClient = new Redis.createClient({
    host: "[removed]",
    port: 6379,
    password: "[removed]",
    db: 0
  });

  redisConnection = new Bottleneck.RedisConnection({
    client: redisClient
  });
  
  limiterGroup = new Bottleneck.Group({
    minTime: 0,
    connection: redisConnection,
    timeout: 300000
  });
```

minTime is set in update when creating from the group
```
const createLimiter = ({ id, minTime = 0 }) => {
  const limiter = limiterGroup.key(id);
  if (minTime !== 0) {
    limiter.updateSettings({ minTime });
  }
  return limiter;
};
```

Here's the scheduling call:

```
    const proxySpecificRequest = Proxy.buildRequestOptions(options, bestProxy);

    const scheduledRequest = bottlenecks[host][bestProxy]
      .schedule(()=>request(proxySpecificRequest))
      .then(result=>result)
      .catch((error) => {
        if (error instanceof Bottleneck.BottleneckError) {
          console.log(`MEH`);
        }
        console.error(error);
        process.exit(1);
      });
    return scheduledRequest;
```

**Comment by SGrondin** [comment]
Very nice catch. This error only occurred when a limiter doesn't have `maxConcurrent` or `reservoir` after calling `updateSettings()`. I've fixed it and released `v2.13.2`. Thank you for reporting it and providing code to reproduce it.

By the way, `limiter.updateSettings()` returns a promise, you might want to wait for it to resolve and/or catch potential errors.
